### ISSUE TITLE
Deprecated plugin boot.js

### ISSUE THREAD

**Issue by amitkukadia** [steveclarke/quasar-firebase-example#5] opened 2018-12-01 13:49 UTC
The boot.js plugin is now deprecated, in favor of prefetch feature. However, it is not as effective as the boot.js plugin. 
The migration guide is given below
https://medium.com/quasar-framework/updating-to-quasar-0-17-x-with-firebase-authentication-91c129606859
Still, with this method, I am not getting the same results. It suggests that we should add prefetch to every component for auth. I think there must be a better way. Can you try to integrate prefetch into this app keeping the results same?? Or at least suggest a better way here.

**Comment by steveclarke** [comment] 2018-12-01 17:55
Yes I think the preFetch on every page is not very elegant. The way I understand the `onAuthStateChanged` observer is that it only needs to be registered once for the app. It's overkill to be registering this observer on every page. But maybe i'm mis-understanding the method.

I believe that this observer is what allows the app to automatically and instantly log the user out if their account is disabled form the Firebase console.

Now that `preFetch` could probably be extracted into a mixin, but it would still have to be mixed in to every page.

I like the use of the meta data in the routes because they allow me to easily see from my `routes.js` what pages require auth.

Feel free to fork and try moving it to preFetch. I'll have a look when I have a moment. I'm currently working on a sample Quasar app that authenticates against a Ruby on Rails API.

**Comment by steveclarke** [comment] 2018-12-01 20:11
Ok check out the preFetch branch that I created:

https://github.com/steveclarke/quasar-firebase-example/tree/prefetch

This has the same problem that I had before I solved by using `boot.js`. After you authenticate to the site, when you reload the page it should automatically sign you in again from credentials stored locally by Firebase. This works, however there is a brief redirect to the authentication page, and then you're taken to the dashboard page again.

`boot.js` doesn't have this problem because it waits for the authentication to complete before launching the app.

I think the problem is in how Firebase `.onAuthStateChanged` works. Maybe there's a method that will explicitly try and authenticate the user from stored credentials that returns a promise. An observer just isn't working in this scenario.

![kapture 2018-12-01 at 16 34 55](https://user-images.githubusercontent.com/1305/49332478-f7b4a000-f587-11e8-9a3a-68cdcef0ebdf.gif)

**Comment by amitkukadia** [comment] 2018-12-01 20:34
The way I kind of solved it, for now, is by 
1. Remove the routes metadata checking
2. Add the prefetch to both the layouts (auth and default)

This way whenever we load the app, first it will go to the default route, if not logged in redirects then goes to the login page. Assuming most of the time user will be in logged in state this is a better way to go I think.
Likewise, if we try to go to login page when we are logged in, we will be redirected back.

So the key here is redirecting only if the required state is false. 
Please let me know if there can be an issue with this approach.

for auth layout following code
    auth.onAuthStateChanged(user => {
      if (user) {
        // Signed in. Let Vuex know.
        store.state.user = user;
        redirect("/");
      } 
    });

and for default
    auth.onAuthStateChanged(user => {
      if (user) {
        // Signed in. Let Vuex know.
        console.log("loggedin");
        store.state.user = user;
        } 
          else {
        // Signed out. Let Vuex know.
        store.state.user = null;
        redirect("/auth");
      }
    });

**Comment by steveclarke** [comment] 2018-12-01 21:02
Can you submit a pull request with that change in it? I'd like to give it a try.

**Comment by razbakov** [comment] 2018-12-21 13:59
You can store userId in localstorage and init app and then call firebase onAuthStateChanged to update user info

**Comment by Larceniii** [comment] 2019-05-23 00:04
I'm guessing that pull request never happened huh.... @amitkukadia

**Comment by justice47** [comment] 2019-10-09 08:01
Seems that
```
Router.beforeEach((to, from, next) => {
    firebase.auth().onAuthStateChanged(user => {
      const currentUser = firebase.auth().currentUser
      const requiresAuth = to.matched.some(record => record.meta.requiresAuth)
      console.log(currentUser)
      console.log(requiresAuth)

      if (requiresAuth && !currentUser) next('/login')
      else if (!requiresAuth && currentUser) next('/')
      else next()
   })
})
```
is worked for me!

**Comment by kosirm** [comment] 2019-10-16 10:49
@justice47  thanks! works fine :)

**Closed** 2020-01-12 12:49 UTC
